version: '3.8'

services:
  webserver:
    image: nginx:alpine
    container_name: nexus_modern_website
    ports:
      - "80:80"
    volumes:
      - ./src:/usr/share/nginx/html:ro
    restart: always
